CREATE DATABASE CAT_M;
USE CAT_M;

CREATE TABLE register (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    badge VARCHAR(50) NOT NULL,
    date DATE NOT NULL,
    hour TIME NOT NULL
);
